[package]
name = "raytracing_in_one_weekend"
version = "0.1.0"
authors = ["Soeren Vullriede <soeren.vu@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
lazy_static = "1.3.0"
lodepng = "2.4.2"
rayon = "1.0.3"